hyperparameters:
  batch_size: 1024
  epochs: 1000
  lr: 1e-3
  weight_decay: 3e-4
  hidden_dim: [1, 2, 3]
  num_layers: [32,64,128]
  dropout: [.15, .2, .25]

store_model: False
verbose: True

name: 'lstm_bidirectional'
