hyperparameters:
  batch_size: 1024
  epochs: 1000
  lr:
  weight_decay: [3e-4, 8e-04, 3e-3]
  num_features:
  num_layers: [1, 2, 3]
  num_filters: [32,64,128]
  kernel_sizes: list(permutations([3,5,7,9,11],4))
  dropout: [.15, .2, .25]

store_model: False
verbose: False

name: 'tcn'